// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMCd3N1pJfdAsi9Ku8QyCOpETA_dl86Mw',
    appId: '1:637348987741:web:92fa22150d6e3ebfec9eb4',
    messagingSenderId: '637348987741',
    projectId: 'wareef-24238',
    authDomain: 'wareef-24238.firebaseapp.com',
    storageBucket: 'wareef-24238.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdTSnVR8ZZRaEkYgzjbedYsLt9bBKtMxo',
    appId: '1:637348987741:android:7a878473c3c1e083ec9eb4',
    messagingSenderId: '637348987741',
    projectId: 'wareef-24238',
    storageBucket: 'wareef-24238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVfFlZt6M7C0HPXx8KzuMNrKSTwEyNxdM',
    appId: '1:637348987741:ios:1b29c456ee9d8334ec9eb4',
    messagingSenderId: '637348987741',
    projectId: 'wareef-24238',
    storageBucket: 'wareef-24238.appspot.com',
    iosBundleId: 'com.example.wareef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVfFlZt6M7C0HPXx8KzuMNrKSTwEyNxdM',
    appId: '1:637348987741:ios:82cfc2a998ac0d3aec9eb4',
    messagingSenderId: '637348987741',
    projectId: 'wareef-24238',
    storageBucket: 'wareef-24238.appspot.com',
    iosBundleId: 'com.example.wareef.RunnerTests',
  );
}
